[package]
name = "equs-oid4vci"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0 OR MIT"
description = "OpenID for Verifiable Credentials Issuance"
repository = "https://github.com/equs-ai/oid4vci-rs"

[lib]
name = "oid4vci"

[features]
reqwest = ["oauth2/reqwest"]

[dependencies]
# TODO feature-gate
isomdl = "0.2.0"

ssi = "=0.16.0"
serde = { version = "=1.0.221", features = ["derive"] }
serde_json = "1.0"
serde_with = "3.3.0"
serde_path_to_error = "0.1.14"
url = { version = "2.3.1", features = ["serde"] }
oauth2 = { version = "5.0.0-alpha.4", features = [
    "timing-resistant-secret-traits",
] }
async-signature = "0.3.0"
rand = "0.8.5"
time = { version = "0.3.29", features = ["serde"] }
thiserror = "1.0.49"
tracing = "0.1"
base64 = "0.21.4"
serde_urlencoded = "0.7.1"
async-trait = "0.1.81"
anyhow = "1.0.86"
sha2 = "0.10.8"
form_urlencoded = "1.2.1"
percent-encoding = "2.3.1"

[dev-dependencies]
assert-json-diff = "2.0.2"
did-jwk = "0.4"
did-method-key = "0.5"
tokio = { version = "1.25.0", features = ["macros"] }
equs-oid4vci = { path = ".", features = ["reqwest"] }
rstest = "0.26.1"